{
 "title": "Board Game Stats",
 "time": { "from": "2022-08-10T17:14:39.264Z", "to": "2022-08-11T05:14:39.264Z" },
 "templating": {
  "list": [
   {
    "name": "players",
    "query": "SELECT players.name FROM players"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Games by Play",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  games.name AS game_name,\n  COUNT(plays.id) AS num_plays\nFROM games LEFT OUTER JOIN plays\n  ON games.id = plays.game_ref_id \nGROUP BY games.id\nORDER BY num_plays DESC"
    }
   ]
  },
  {
   "title": "Top Locations by Play",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  locations.name AS location_name,\n  COUNT(plays.id) AS num_plays\nFROM locations LEFT OUTER JOIN plays\n  ON locations.id = plays.location_ref_id \nGROUP BY locations.id\nORDER BY num_plays DESC"
    }
   ]
  },
  {
   "title": "Top Players by Play",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  players.name AS player_name,\n  COUNT(player_scores.id) AS num_plays\nFROM players LEFT OUTER JOIN player_scores\n  ON players.id = player_scores.player_ref_id \nGROUP BY players.id\nORDER BY num_plays DESC"
    }
   ]
  }
 ]
}