[workspace]
resolver = "2"
members = [
  ".",
  "argparse/",
  "cards/",
  "gaia_project/",
  "input/",
  "math/",
  "oath/",
  "path_finding/",
  "stat_gen/",
  "sudoku/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
