[package]
name = "dotfiles"
version = "0.1.0"
authors = ["Carson Boden <carson.boden@gmail.com>"]
edition = "2021"

[[examples]]
name = "path-finding"
path = "examples/path_finding/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_matches = "1.5"

[dependencies]
ron = "0.7"
serde = { version = "1.0", features = ["derive"] }
