[package]
name = "dotfiles"
version = "0.1.0"
authors = ["Carson Boden <carson.boden@gmail.com>"]
edition = "2021"

[workspace]
members = [
  ".",
  "gaia_project/",
  "path_finding/",
]

[[example]]
name = "path-finding"
path = "examples/path-finding/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_matches = "1.5"

[dependencies]
bevy = "0.6.1"
rand = "0.8.5"
strum = "0.13.0"
strum_macros = "0.13.0"
