# Allow unstable features
  unstable_features = true

# Reorder import statements alphabetically.
# Default: false
  reorder_imports = true

# Reorder lists of names in import statements alphabetically.
# Default: false
  reorder_imported_names = true

# Retain some formatting characteristics from the source code.
# Default: true
  take_source_hints = false

# Break comments to fit on the line.
# Default: false
  wrap_comments = true

# Convert /* */ comments to // comments where possible.
# Default: false
  normalize_comments = true

# Replace uses of the try! macro by the ? shorthand.
# Default: false
  use_try_shorthand = true

# How imports should be grouped into use statements. Imports will be merged or
# split to the configured level of granularity.
# Default: Preserve
  imports_granularity = "Module"

# Controls the strategy for how imports are grouped together.
# Default: Preserve
  group_imports = "StdExternalCrate"
