name: Submission Approval Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bootstrap:
    name: Run Bootstrap
    runs-on: ubuntu-latest
    steps:
      # Checks out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Bootstrap
        run: |
          # XXX: Ensure this repo is on the $PYTHONPATH, which Python uses to
          # determine where modules live. For some reason this must be done
          # each time a Python command is run.
          export PYTHONPATH=$PYTHONPATH:~/.dotfiles

          pip install -r requirements.txt
          python bootstrap/main.py

      - name: See if Bootstrap worked
        run: |
          # XXX: Ensure this repo is on the $PYTHONPATH, which Python uses to
          # determine where modules live. For some reason this must be done
          # each time a Python command is run.
          export PYTHONPATH=$PYTHONPATH:~/.dotfiles

          python -m unittest discover -s 'bootstrap/' -p '*test.py'

      - name: Run Python unittests
        run: |
          # XXX: Ensure this repo is on the $PYTHONPATH, which Python uses to
          # determine where modules live. For some reason this must be done
          # each time a Python command is run.
          export PYTHONPATH=$PYTHONPATH:~/.dotfiles

          python -m unittest discover -s 'tools/' -p '*test.py'
          python -m unittest discover -s 'examples/' -p '*test.py'
          python -m unittest discover -s 'utils/' -p '*test.py'

  rust-tests:
    name: Rust Tests
    runs-on: ubuntu-latest
    steps:
      # Checks out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Run Rust core tests
        run: cargo test

      - name: Run Rust example tests
        run: cargo test --examples

      - name: Run Rust doc tests
        run: cargo test --doc
