---
name: Submission Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    bootstrap:
        runs-on: ubuntu-latest
        steps:
            # Checks out repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: 3.x

            - uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
                  installer-parallel: true

            - name: Load cached Python venv
              id: cached-poetry-dependencies
              uses: actions/cache@v3
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

            - name: Install Python dependencies
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
              run: poetry install --no-interaction --no-root

            - name: Configure $PYTHONPATH and venv
              run: |
                  echo "PYTHONPATH=$PYTHONPATH:~/.dotfiles" >> $GITHUB_ENV
                  source .venv/bin/activate

            - name: Check Cargo cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Check pre-commit cache
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit
                  key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

            - name: Run Bootstrap
              run: poetry run python bootstrap/main.py

            - name: See if Bootstrap worked
              run: poetry run python -m unittest 'bootstrap/main_integration_test.py'

            - name: Run Python unittests
              run: poetry run python -m unittest discover -p '*test.py'

            - name: Run Rust core tests
              run: cargo test

            - name: Run Rust example tests
              run: cargo test --examples

            - name: Run Rust doc tests
              run: cargo test --doc

    website:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./docs
        steps:
            - uses: actions/checkout@v2

            - name: Set up Ruby
              uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
              with:
                  working-directory: ./docs
                  ruby-version: '3.1'
                  bundler-cache: true

            - name: Ensure Site builds correctly
              run: |
                  bundle exec jekyll build
                  bundle exec htmlproofer ./_site --disable-external --allow-hash-href --alt-ignore '/.*/portfolio/.*/'
