---
name: Submission Tests

on:
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    bootstrap:
        # TODO: Run on OSX; Currently issues with alsa-lib
        # strategy:
        #     matrix:
        #         os: [ubuntu-latest, macos-latest]
        # runs-on: ${{ matrix.os }}
        runs-on: ubuntu-latest
        steps:
            # Checks out repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v3

            # Installs Nix, the package provider
            - uses: cachix/install-nix-action@v22

            # Adds a cache for `devenv`, the package manager
            - uses: cachix/cachix-action@v12
              with:
                name: devenv

            # Installs `devenv` to run CI in environments
            - name: Install devenv.sh
              run: nix profile install tarball+https://install.devenv.sh/latest

            # Run CI
            - run: devenv shell poetry run python ci.py HEAD origin/main $GITHUB_WORKSPACE
              working-directory: bootstrap/
