---
name: Submission Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    bootstrap:
        runs-on: ubuntu-latest
        steps:
            # Checks out repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x
                  cache: pip

            - name: Configure $PYTHONPATH
              run: echo "PYTHONPATH=$PYTHONPATH:~/.dotfiles" >> $GITHUB_ENV

            - name: Check Cargo cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Check pre-commit cache
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit
                  key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

            - name: Run Bootstrap
              run: |
                  pip install -r requirements.txt
                  python bootstrap/main.py

            - name: See if Bootstrap worked
              run: python -m unittest 'bootstrap/main_integration_test.py'

            - name: Run Python unittests
              run: |
                  python -m unittest discover -p '*test.py'

            - name: Run Rust core tests
              run: cargo test

            - name: Run Rust integration tests
              run: python -m unittest discover -s 'examples/' -p '*test.py'

            - name: Run Rust example tests
              run: cargo test --examples

            - name: Run Rust doc tests
              run: cargo test --doc

    website:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./docs
        steps:
            - uses: actions/checkout@v2

            - name: Set up Ruby
              uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
              with:
                  ruby-version: '3.1'
                  bundler-cache: true

            - name: Ensure Site builds correctly
              run: |
                  bundle exec jekyll build
                  bundle exec htmlproofer ./_site --disable-external --allow-hash-href --alt-ignore '/.*/portfolio/.*/'
