---
name: Submission Tests

on:
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    detect-changes:
        runs-on: ubuntu-latest
        outputs:
            workflows: ${{ steps.filter.outputs.workflows }}
            bootstrap: ${{ steps.filter.outputs.bootstrap }}
            python: ${{ steps.filter.outputs.python }}
            rust: ${{ steps.filter.outputs.rust }}
            website: ${{ steps.filter.outputs.website }}
        steps:
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      # Run Workflow for all suites if the script has changed
                      workflows:
                        - '.github/workflows/submission-tests.yml'
                      bootstrap:
                        - 'Cargo.lock'
                        - 'Cargo.toml'
                        - 'bootstrap/**'
                        - 'dependencies.txt'
                        - 'poetry.lock'
                        - 'pyproject.toml'
                      python:
                        - '**.py'
                      rust:
                        - '**.rs'
                      website:
                        - 'docs/**'

    bootstrap:
        needs: detect-changes
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        if: >-
            needs.detect-changes.outputs.bootstrap == 'true' ||
            needs.detect-changes.outputs.workflows == 'true'
        runs-on: ${{ matrix.os }}
        steps:
            # Checks out repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v3
              
            - uses: cachix/install-nix-action@v22

            - uses: cachix/cachix-action@v12
              with:
                name: devenv

            - name: Install devenv.sh
              run: nix profile install tarball+https://install.devenv.sh/latest
              shell: sh

            - run: devenv ci

            - name: See if Bootstrap worked
              run: |
                cd bootstrap
                # Ensure package dependencies are available
                echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
                devenv shell poetry run python -m unittest 'main_integration_test.py'

    python:
        needs: detect-changes
        if: >-
            needs.detect-changes.outputs.python == 'true' ||
            needs.detect-changes.outputs.workflows == 'true'
        runs-on: ubuntu-latest
        steps:
            # Checks out repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v3

            - uses: cachix/install-nix-action@v22

            - uses: cachix/cachix-action@v12
              with:
                name: devenv

            - name: Install devenv.sh
              run: nix profile install tarball+https://install.devenv.sh/latest
              shell: sh
              
            - name: Install Python dependencies and run unittests
              run: |
                  for test in $(find $GITHUB_WORKSPACE -name "*_test.py" -not -path "**/bootstrap/**" -not -path "**/.venv/**"); do
                    cd $(dirname $test)
                    poetry install --no-interaction --no-root
                    # Ensure package dependencies are available
                    echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
                    source $(poetry env info --path)/bin/activate
                    echo "Running tests for $test:"
                    poetry run python -m unittest $test
                  done
              shell: devenv shell

    rust:
        needs: detect-changes

        if: >-
            needs.detect-changes.outputs.rust == 'true' ||
            needs.detect-changes.outputs.workflows == 'true'

        runs-on: ubuntu-latest

        steps:
            # Checks out repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v3

            - uses: cachix/install-nix-action@v22

            - uses: cachix/cachix-action@v12
              with:
                name: devenv

            - name: Install devenv.sh
              run: nix profile install tarball+https://install.devenv.sh/latest
              shell: sh

            - name: Generate `Cargo.lock` to check cache dependencies
              run: cargo generate-lockfile
              shell: devenv shell

            - name: Check Cargo cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Run Rust core tests
              run: cargo test
              shell: devenv shell

            - name: Run Rust example tests
              run: cargo test --examples
              shell: devenv shell

            - name: Run Rust doc tests
              run: cargo test --doc
              shell: devenv shell

    website:
        needs: detect-changes
        if: >-
            needs.detect-changes.outputs.website == 'true' ||
            needs.detect-changes.outputs.workflows == 'true'
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./docs
        steps:
            - uses: actions/checkout@v2

            - name: Set up Ruby
              uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
              with:
                  working-directory: ./docs
                  ruby-version: '3.1'
                  bundler-cache: true

            - name: Ensure Site builds correctly
              run: |
                  bundle exec jekyll build
                  bundle exec htmlproofer ./_site --disable-external --allow-hash-href
