---
name: Submission Tests

on:
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    bootstrap:
        # TODO: Run on OSX; Currently issues with alsa-lib
        # strategy:
        #     matrix:
        #         os: [ubuntu-latest, macos-latest]
        # runs-on: ${{ matrix.os }}
        runs-on: ubuntu-latest
        steps:
            # Checks out repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v3
              with:
                  # Checkout all history, so we can compare to `main`
                  fetch-depth: 0

            # Bootstraps environment, as outlined in `README.md`
            - name: Bootstrap Environment
              run: ./bootstrap/bootstrap.sh

            - name: Run Continuous Integration
              run: |
                  # New step runner must re-source Nix Home Manager
                  . ~/.nix-profile/etc/profile.d/nix.sh
                  fish devenv shell poetry run python ci.py HEAD origin/main --root $GITHUB_WORKSPACE
              working-directory: bootstrap/
