---
name: Submission Approval Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    bootstrap:
        runs-on: ubuntu-latest
        steps:
            # Checks out repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x
                  cache: pip

            - name: Configure $PYTHONPATH
              run: echo "PYTHONPATH=$PYTHONPATH:~/.dotfiles" >> $GITHUB_ENV

            - name: Check Cargo cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Check pre-commit cache
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit
                  key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

            - name: Bootstrap
              run: |
                  pip install -r requirements.txt
                  python bootstrap/main.py

            - name: Ensure Bootstrap worked
              run: python -m unittest 'bootstrap/main_integration_test.py'

    python:
        runs-on: ubuntu-latest
        needs: bootstrap
        steps:
            - name: Python unittests
              run: python -m unittest discover -p '*test.py'

    rust:
        runs-on: ubuntu-latest
        needs: bootstrap
        steps:
            - name: Rust core tests
              run: cargo test

            - name: Rust integration tests
              run: python -m unittest discover -s 'examples/' -p '*test.py'

            - name: Rust example tests
              run: cargo test --examples

            - name: Rust doc tests
              run: cargo test --doc
