name: Website Test and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install Yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build from scratch
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Run yarn tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      - name: Deploy website to `gh-pages` branch
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: deploy
