---
name: Website Test

on:
    push:
        branches: [main]
        paths:
            - docs/**
    pull_request:
        branches: [main]
        paths:
            - docs/**

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./docs
        steps:
            - uses: actions/checkout@v2
